# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(default='', max_length=200)),
                ('conteudo', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Postagens',
            },
        ),
    ]
